version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-baso
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=baso
      - POSTGRESQL_PASSWORD=baso_secret
      - POSTGRESQL_DATABASE=baso-social
    networks:
      - social
  redis:
    image: redis:6.0
    container_name: redis-baso
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-baso:/data
    environment:
      - REDIS_PASSWORD=baso_redis
    networks:
      - social
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $$REDIS_PASSWORD'

networks:
  social:

volumes:
  social_mysql:
  redis-baso: